<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [

            /*Combos */
            array(
                'nombre' =>  "¡Arma tu Combo!",
                'precio' => 0,
                'imagen' => "Combo_Original",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => false,
                'nombre_corto' => "Arma Tu Combo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => true,
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2,
            ),
            array(
                'nombre' =>  "Paisa Siderense",
                'precio' => 29000,
                'imagen' => "Paisa_Siderense",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Paisa",
                'cantidad_personas' => 2,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Costillas Baby",
                'precio' => 29000,
                'imagen' => "Costillas_Baby_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Costillas para 2",
                'cantidad_personas' => 2,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Mazorcada",
                'precio' => 29000,
                'imagen' => "Mazorcada_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Mazorcada para 2",
                'cantidad_personas' => 2,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Chicharron",
                'precio' => 29000,
                'imagen' => "Chicharron",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Max Chicharron",
                'cantidad_personas' => 2,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Chicken Pig",
                'precio' => 29000,
                'imagen' => "Chicken_Pig",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Chicken Pig",
                'cantidad_personas' => 2,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Max Tocineta",
                'precio' => 29000,
                'imagen' => "Tocineta_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Tocineta para 2",
                'cantidad_personas' => 2,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Trifasica",
                'precio' => 19500,
                'imagen' => "Trifasica",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Trifasica",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Pollo Agridulce",
                'precio' => 19500,
                'imagen' => "Pollo_Agridulce",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Pollo Agridulce",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Cerdo a la Naranja",
                'precio' => 19500,
                'imagen' => "Cerdo_Naranja",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Cerdo a la Naranja",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Mazorcada Personal",
                'precio' => 19500,
                'imagen' => "Mazorcada",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Mazorcada Personal",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Costillas Personal",
                'precio' => 19500,
                'imagen' => "Costillas_Baby_1",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Costillas Personal",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Tocineta Personal",
                'precio' => 19500,
                'imagen' => "Tocineta",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Tocineta Personal",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Bombon de Pollo",
                'precio' => 15500,
                'imagen' => "Bombon_Pollo",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "Bombon de Pollo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Longui",
                'precio' => 14500,
                'imagen' => "Longui",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => false,
                'nombre_corto' => "Max Longui",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Salchi",
                'precio' => 9500,
                'imagen' => "Salchi",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 2,
                'mixto' => false,
                'nombre_corto' => "Salchi",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Kids Ranchero",
                'precio' => 14500,
                'imagen' => "Kids",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 2,
                'mixto' => false,
                'nombre_corto' => "Ranchero",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Chicken BBQ",
                'precio' => 18000,
                'imagen' => "Chicken_BQQ",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "AlitasX4",
                'cantidad_personas' => 1,
                'cantidad_alas' => 4,
                'necesita_papas' => true,
                'necesita_alas' => true,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Búfalo Wings",
                'precio' => 23500,
                'imagen' => "Bufalo_Wings",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "AlitasX6",
                'cantidad_personas' => 1,
                'cantidad_alas' => 6,
                'necesita_papas' => true,
                'necesita_alas' => true,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Chorizo",
                'precio' => 16000,
                'imagen' => "Chorizo",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 2,
                'mixto' => true,
                'nombre_corto' => "Max Chorizo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Maicitos",
                'precio' => 18500,
                'imagen' => "Maicitos",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 2,
                'mixto' => true,
                'nombre_corto' => "Max Maicitos",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => true,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Boom Granjero",
                'precio' => 83000,
                'imagen' => "Boom_Granjero",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 4,
                'mixto' => true,
                'nombre_corto' => "Boom Granjero",
                'cantidad_personas' => 6,
                'cantidad_alas' => 6,
                'necesita_papas' => true,
                'necesita_alas' => true,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 3
            ),
            array(
                'nombre' =>  "Crispy Chicken",
                'precio' => 34000,
                'imagen' => "Crispy_Chicken",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 3,
                'mixto' => true,
                'nombre_corto' => "AlitasX12",
                'cantidad_personas' => 1,
                'cantidad_alas' => 12,
                'necesita_papas' => true,
                'necesita_alas' => true,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Papas Chips",
                'precio' => 3500,
                'imagen' => "Chips",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Papa Tajada",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),
            array(
                'nombre' =>  "Papa Criolla",
                'precio' => 5000,
                'imagen' => "Criollas",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Porcion Criolla",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 1,
                'cantidad_salsas'=> 2
            ),

            /* Adiciones */
            array(
                'nombre' =>  "Tocineta",
                'precio' => 6000,
                'imagen' => "Adicion_Tocineta",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Tocineta",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0,
            ),
            array(
                'nombre' =>  "Chicharron",
                'precio' => 7500,
                'imagen' => "Adicion_Chicharron",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Chicharron",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Salchicha Ranchera",
                'precio' => 5000,
                'imagen' => "Adicion_Salchicha_Ranchera",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Salchicha Ranchera",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Chorizo Parrillero",
                'precio' => 5000,
                'imagen' => "Adicion_Chorizo_Parrillero",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Chorizo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Costillas Baby",
                'precio' => 7500,
                'imagen' => "Adicion_Costillas_Baby",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Costillas",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Longaniza",
                'precio' => 4500,
                'imagen' => "Adicion_Longaniza",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Longaniza",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Bombon de Pollo",
                'precio' => 6000,
                'imagen' => "Adicion_Bombon",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Bombon Pollo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Salchicha Tradicional",
                'precio' => 4000,
                'imagen' => "Adicion_Salchicha_Tradicional",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Salchicha Tradicional",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Huevos Codorniz X3",
                'precio' => 2000,
                'imagen' => "Adicion_Huevos_Codorniz_X3",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "HuevosX3",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Carne Desmechada",
                'precio' => 6500,
                'imagen' => "Adicion_Carne_Desmechada",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Carne Desmechada",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Pollo Desmechado",
                'precio' => 6500,
                'imagen' => "Adicion_Pollo_Desmechado",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Pollo Desmechado",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Croqueta Agridulce",
                'precio' => 6500,
                'imagen' => "Adicion_Croqueta_Agridulce",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "C.Pollo Agridulce",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Croquetas Naranja",
                'precio' => 6500,
                'imagen' => "Adicion_Croquetas_Naranja",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "C.Cerdo Naranja",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Papa Artesanal",
                'precio' => 6500,
                'imagen' => "Papa_Francesa",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "P Francesa",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Papa Criolla",
                'precio' => 5000,
                'imagen' => "Adicion_Papa_Criolla",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "P Criolla",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Maduritos",
                'precio' => 2500,
                'imagen' => "Adicion_Maduritos",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Maduritos",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Pico de Gallo",
                'precio' => 2500,
                'imagen' => "Adicion_Pico_de_Gallo",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Pico de Gallo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Guacamole",
                'precio' => 2500,
                'imagen' => "Adicion_Guacamole",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Guacamole",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Mazorca",
                'precio' => 2500,
                'imagen' => "Adicion_Mazorca",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Mazorca",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Arepa",
                'precio' => 500,
                'imagen' => "Adicion_Arepa",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Arepa",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Queso Costeño",
                'precio' => 5000,
                'imagen' => "Adicion_Queso_Costeño",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Queso Costeño",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Alitas X1",
                'precio' => 2500,
                'imagen' => "Adicion_Alitas_X1",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "AlitaX1",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Maicitos",
                'precio' => 2500,
                'imagen' => "Adicion_Maicitos",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Maicitos",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Queso Gratinado",
                'precio' => 5000,
                'imagen' => "Queso_Gratinado",
                'categoria_id' => 7,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Queso Gratinado",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),

            /* Salsas Productos */

            array(
                'nombre' =>  "Rosada",
                'precio' => 1500,
                'imagen' => "Salsa_Rosada",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Rosada",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Tartara",
                'precio' => 1500,
                'imagen' => "Salsa_Tartara",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Tartara",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Ceviche",
                'precio' => 1500,
                'imagen' => "Salsa_Ceviche",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Ceviche",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Ajo",
                'precio' => 1500,
                'imagen' => "Salsa_Ajo",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Ajo",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Maiz",
                'precio' => 1500,
                'imagen' => "Salsa_Maiz",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Maiz",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "BQQ",
                'precio' => 1500,
                'imagen' => "Salsa_BQQ",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "BQQ",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Roja",
                'precio' => 1500,
                'imagen' => "Salsa_Roja",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Roja",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Piña",
                'precio' => 1500,
                'imagen' => "Salsa_Piña",
                'categoria_id' => 8,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Piña",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),

            /*Bebidas */

            array(
                'nombre' =>  "CocaCola",
                'precio' => 4000,
                'imagen' => "Bebidas_Coca_Cola",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "CocaCola",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "CocaCola Familiar",
                'precio' => 8500,
                'imagen' => "Bebidas_Coca_Cola_familiar",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "CocaCola Familiar",
                'cantidad_personas' => 5,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Manzana",
                'precio' => 4000,
                'imagen' => "Bebidas_Manzana",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Manzana",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Uva",
                'precio' => 4000,
                'imagen' => "Bebidas_Uva",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Uva",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Colombiana",
                'precio' => 4000,
                'imagen' => "Bebidas_Colombiana",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Colombiana",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "H20",
                'precio' => 4000,
                'imagen' => "Bebidas_H20",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "H20",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Mango",
                'precio' => 4000,
                'imagen' => "Bebidas_Mango",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Mango Valle",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Mora",
                'precio' => 4000,
                'imagen' => "Bebidas_Mora",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Mora Valle",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "Fresa Mango",
                'precio' => 4000,
                'imagen' => "Bebidas_Fresa_Mango",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Fresa Mango Valle",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' =>  "CocaCola Zero",
                'precio' => 4000,
                'imagen' => "Bebidas_CocaCola_Zero",
                'categoria_id' => 9,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "CocaCola Zero",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => true,
                'card_id' => 3,
                'cantidad_salsas'=> 0
            ),


            /* Tipos de Papas*/
            array(
                'nombre' =>  "Papa Francesa",
                'precio' => 0,
                'imagen' => "Papa_Francesa",
                'categoria_id' => 10,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Francesa",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),

            array(
                'nombre' => "Papa Criolla",
                'precio' => 0,
                'imagen' => "Papa_criolla",
                'categoria_id' => 10,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Criolla",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),

            array(
                'nombre' => "Papa Mixta",
                'precio' => 0,
                'imagen' => "Papa_Mixta",
                'categoria_id' => 10,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Mixta",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' => "BQQ",
                'precio' => 0,
                'imagen' => "Alas_BQQ",
                'categoria_id' => 11,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Alas BQQ",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' => "Miel Mostaza",
                'precio' => 0,
                'imagen' => "Alas_Miel_Mostaza",
                'categoria_id' => 11,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Miel Mostaza",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
            array(
                'nombre' => "Picante",
                'precio' => 0,
                'imagen' => "Alas_Picante",
                'categoria_id' => 11,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'empaque_id' => 1,
                'mixto' => false,
                'nombre_corto' => "Picante",
                'cantidad_personas' => 1,
                'cantidad_alas' => 0,
                'necesita_papas' => false,
                'necesita_alas' => false,                
                'modal_rapido' => false,
                'card_id' => 2,
                'cantidad_salsas'=> 0
            ),
        ];

        DB::table('productos')->insert($datos);
    }
}
